#hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
#hibernate.connection.url=jdbc:mysql://localhost:3306/game_coach
#hibernate.connection.username=root
#hibernate.connection.password=mysql
#hibernate.default_catalog=game_coach