package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CoachSportsProfile generated by hbm2java
 */
@Entity
@Table(name="coach_sports_profile"
)
public class CoachSportsProfile  implements java.io.Serializable {


     private int id;
     private Coach coach;
     private Sport sport;
     private int yoe;
     private double perHourRate;
     private int status;

    public CoachSportsProfile() {
    }

    public CoachSportsProfile(int id, Coach coach, Sport sport, int yoe, double perHourRate, int status) {
       this.id = id;
       this.coach = coach;
       this.sport = sport;
       this.yoe = yoe;
       this.perHourRate = perHourRate;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="coach_id", nullable=false)
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sports_id", nullable=false)
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }

    
    @Column(name="yoe", nullable=false)
    public int getYoe() {
        return this.yoe;
    }
    
    public void setYoe(int yoe) {
        this.yoe = yoe;
    }

    
    @Column(name="per_hour_rate", nullable=false, precision=22)
    public double getPerHourRate() {
        return this.perHourRate;
    }
    
    public void setPerHourRate(double perHourRate) {
        this.perHourRate = perHourRate;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


