package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CoachStudentInteractions generated by hbm2java
 */
@Entity
@Table(name="coach_student_interactions"
)
public class CoachStudentInteractions  implements java.io.Serializable {


     private int id;
     private Coach coach;
     private Student student;
     private Sport sport;
     private int studentComment;
     private int status;

    public CoachStudentInteractions() {
    }

    public CoachStudentInteractions(int id, Coach coach, Student student, Sport sport, int studentComment, int status) {
       this.id = id;
       this.coach = coach;
       this.student = student;
       this.sport = sport;
       this.studentComment = studentComment;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="coach_id", nullable=false)
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sports_id", nullable=false)
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }

    
    @Column(name="student_comment", nullable=false)
    public int getStudentComment() {
        return this.studentComment;
    }
    
    public void setStudentComment(int studentComment) {
        this.studentComment = studentComment;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


