package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * CoachQualification generated by hbm2java
 */
@Entity
@Table(name="coach_qualification"
)
public class CoachQualification  implements java.io.Serializable {


     private int id;
     private int gameProfileId;
     private String qualification;
     private String documentLink;
     private int status;

    public CoachQualification() {
    }

    public CoachQualification(int id, int gameProfileId, String qualification, String documentLink, int status) {
       this.id = id;
       this.gameProfileId = gameProfileId;
       this.qualification = qualification;
       this.documentLink = documentLink;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="game_profile_id", nullable=false)
    public int getGameProfileId() {
        return this.gameProfileId;
    }
    
    public void setGameProfileId(int gameProfileId) {
        this.gameProfileId = gameProfileId;
    }

    
    @Column(name="qualification", nullable=false, length=255)
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    
    @Column(name="document_link", nullable=false, length=65535)
    public String getDocumentLink() {
        return this.documentLink;
    }
    
    public void setDocumentLink(String documentLink) {
        this.documentLink = documentLink;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


