package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
@Entity
@Table(name="coach"
)
public class Coach  implements java.io.Serializable {


     private int id;
     private int userId;
     private String name;
     private Date dob;
     private boolean sex;
     private String district;
     private String email;
     private String mobile;
     private String profilePic;
     private Set<CoachSportsProfile> coachSportsProfiles = new HashSet<CoachSportsProfile>(0);
     private Set<CoachStudentInteractions> coachStudentInteractionses = new HashSet<CoachStudentInteractions>(0);

    public Coach() {
    }

	
    public Coach(int id, int userId, String name, Date dob, boolean sex, String district, String email, String mobile, String profilePic) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.dob = dob;
        this.sex = sex;
        this.district = district;
        this.email = email;
        this.mobile = mobile;
        this.profilePic = profilePic;
    }
    public Coach(int id, int userId, String name, Date dob, boolean sex, String district, String email, String mobile, String profilePic, Set<CoachSportsProfile> coachSportsProfiles, Set<CoachStudentInteractions> coachStudentInteractionses) {
       this.id = id;
       this.userId = userId;
       this.name = name;
       this.dob = dob;
       this.sex = sex;
       this.district = district;
       this.email = email;
       this.mobile = mobile;
       this.profilePic = profilePic;
       this.coachSportsProfiles = coachSportsProfiles;
       this.coachStudentInteractionses = coachStudentInteractionses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false, length=4)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="sex", nullable=false)
    public boolean isSex() {
        return this.sex;
    }
    
    public void setSex(boolean sex) {
        this.sex = sex;
    }

    
    @Column(name="district", nullable=false, length=20)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="email", nullable=false, length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobile", nullable=false, length=10)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="profile_pic", nullable=false, length=65535)
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coach")
    public Set<CoachSportsProfile> getCoachSportsProfiles() {
        return this.coachSportsProfiles;
    }
    
    public void setCoachSportsProfiles(Set<CoachSportsProfile> coachSportsProfiles) {
        this.coachSportsProfiles = coachSportsProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coach")
    public Set<CoachStudentInteractions> getCoachStudentInteractionses() {
        return this.coachStudentInteractionses;
    }
    
    public void setCoachStudentInteractionses(Set<CoachStudentInteractions> coachStudentInteractionses) {
        this.coachStudentInteractionses = coachStudentInteractionses;
    }




}


