package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Sport generated by hbm2java
 */
@Entity
@Table(name="sport"
)
public class Sport  implements java.io.Serializable {


     private int id;
     private String name;
     private String code;
     private Set<CoachSportsProfile> coachSportsProfiles = new HashSet<CoachSportsProfile>(0);
     private Set<StudentSportsProfile> studentSportsProfiles = new HashSet<StudentSportsProfile>(0);
     private Set<CoachStudentInteractions> coachStudentInteractionses = new HashSet<CoachStudentInteractions>(0);

    public Sport() {
    }

	
    public Sport(int id, String name, String code) {
        this.id = id;
        this.name = name;
        this.code = code;
    }
    public Sport(int id, String name, String code, Set<CoachSportsProfile> coachSportsProfiles, Set<StudentSportsProfile> studentSportsProfiles, Set<CoachStudentInteractions> coachStudentInteractionses) {
       this.id = id;
       this.name = name;
       this.code = code;
       this.coachSportsProfiles = coachSportsProfiles;
       this.studentSportsProfiles = studentSportsProfiles;
       this.coachStudentInteractionses = coachStudentInteractionses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="code", nullable=false, length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sport")
    public Set<CoachSportsProfile> getCoachSportsProfiles() {
        return this.coachSportsProfiles;
    }
    
    public void setCoachSportsProfiles(Set<CoachSportsProfile> coachSportsProfiles) {
        this.coachSportsProfiles = coachSportsProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sport")
    public Set<StudentSportsProfile> getStudentSportsProfiles() {
        return this.studentSportsProfiles;
    }
    
    public void setStudentSportsProfiles(Set<StudentSportsProfile> studentSportsProfiles) {
        this.studentSportsProfiles = studentSportsProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sport")
    public Set<CoachStudentInteractions> getCoachStudentInteractionses() {
        return this.coachStudentInteractionses;
    }
    
    public void setCoachStudentInteractionses(Set<CoachStudentInteractions> coachStudentInteractionses) {
        this.coachStudentInteractionses = coachStudentInteractionses;
    }




}


