package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * StudentSportsProfile generated by hbm2java
 */
@Entity
@Table(name="student_sports_profile"
)
public class StudentSportsProfile  implements java.io.Serializable {


     private int id;
     private Student student;
     private Sport sport;
     private String level;
     private int status;

    public StudentSportsProfile() {
    }

    public StudentSportsProfile(int id, Student student, Sport sport, String level, int status) {
       this.id = id;
       this.student = student;
       this.sport = sport;
       this.level = level;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sports_id", nullable=false)
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }

    
    @Column(name="level", nullable=false, length=20)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


