package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
)
public class Student  implements java.io.Serializable {


     private int id;
     private User user;
     private String name;
     private Date dob;
     private byte sex;
     private String district;
     private String mobile;
     private String email;
     private String profilePic;
     private Set<StudentSportsProfile> studentSportsProfiles = new HashSet<StudentSportsProfile>(0);
     private Set<CoachStudentInteractions> coachStudentInteractionses = new HashSet<CoachStudentInteractions>(0);

    public Student() {
    }

	
    public Student(int id, User user, String name, Date dob, byte sex, String district, String mobile, String email, String profilePic) {
        this.id = id;
        this.user = user;
        this.name = name;
        this.dob = dob;
        this.sex = sex;
        this.district = district;
        this.mobile = mobile;
        this.email = email;
        this.profilePic = profilePic;
    }
    public Student(int id, User user, String name, Date dob, byte sex, String district, String mobile, String email, String profilePic, Set<StudentSportsProfile> studentSportsProfiles, Set<CoachStudentInteractions> coachStudentInteractionses) {
       this.id = id;
       this.user = user;
       this.name = name;
       this.dob = dob;
       this.sex = sex;
       this.district = district;
       this.mobile = mobile;
       this.email = email;
       this.profilePic = profilePic;
       this.studentSportsProfiles = studentSportsProfiles;
       this.coachStudentInteractionses = coachStudentInteractionses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false, length=4)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="sex", nullable=false)
    public byte getSex() {
        return this.sex;
    }
    
    public void setSex(byte sex) {
        this.sex = sex;
    }

    
    @Column(name="district", nullable=false, length=20)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="mobile", nullable=false, length=10)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="email", nullable=false, length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="profile_pic", nullable=false, length=65535)
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<StudentSportsProfile> getStudentSportsProfiles() {
        return this.studentSportsProfiles;
    }
    
    public void setStudentSportsProfiles(Set<StudentSportsProfile> studentSportsProfiles) {
        this.studentSportsProfiles = studentSportsProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<CoachStudentInteractions> getCoachStudentInteractionses() {
        return this.coachStudentInteractionses;
    }
    
    public void setCoachStudentInteractionses(Set<CoachStudentInteractions> coachStudentInteractionses) {
        this.coachStudentInteractionses = coachStudentInteractionses;
    }




}


