package com.shashika.game_coach_backend.entity;// default package
// Generated 1/09/2026, 10:20:45 am by Hibernate Tools 7.3.13.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="user_role"
)
public class UserRole  implements java.io.Serializable {


     private int id;
     private String roleName;
     private String roleCode;
     private Set<User> users = new HashSet<User>(0);

    public UserRole() {
    }

	
    public UserRole(int id, String roleName, String roleCode) {
        this.id = id;
        this.roleName = roleName;
        this.roleCode = roleCode;
    }
    public UserRole(int id, String roleName, String roleCode, Set<User> users) {
       this.id = id;
       this.roleName = roleName;
       this.roleCode = roleCode;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="role_name", nullable=false, length=20)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    
    @Column(name="role_code", nullable=false, length=20)
    public String getRoleCode() {
        return this.roleCode;
    }
    
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRole")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

}


